version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db-arkiv
    environment:
      POSTGRES_DB: db-arkiv
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  pg-network:

volumes:
  pg-data: